"""AnalysisEngine - the orchestrator every interface (CLI, API, notebooks) goes through.

Pipeline for ``analyze(symbol)``::

    ┌──────────── fetch stage (concurrent, each isolated) ─────────────┐
    │ history*  quote  news  fundamentals  options  benchmark-history  │   * only fatal one
    └──────────────────────────────┬───────────────────────────────────┘
                                   ▼
    compute stage (worker thread, pure functions):
        indicators → signal / regime / plays / levels → statistics
        → sentiment → options analytics (market or model chain)
        → feature vector (versioned schema)
                                   ▼
    risk stage: every registered RiskModel, concurrently, isolated
                                   ▼
    insight stage: Claude (cached, timeout) or rule-based fallback
                                   ▼
    report dict (JSON-safe) + provenance + warnings + per-stage timings

A failure in any non-history section becomes a ``warnings`` entry and that section is
``null`` - the report is still produced.  That is the core stability guarantee.
"""
from __future__ import annotations

import asyncio
import logging
from dataclasses import dataclass
from datetime import date, timedelta, timezone
from typing import Any

import numpy as np
import pandas as pd

from .analysis import indicators as ta
from .analysis import options as opt
from .analysis import forecast as fcast
from .analysis import sentiment as sent
from .analysis import signals, stats
from .analysis.insights import claude_insight, rule_based_insight
from .cache import TieredCache
from .config import Settings, get_settings
from .errors import ABGError, DataValidationError
from .http import HttpClient
from .models import Capability, Fetched, Provenance, Fundamentals, NewsItem, OptionChain, PriceHistory, Quote
from .providers.base import Provider
from .providers.local import parse_price_csv
from .providers.router import ProviderRouter, build_providers
from .risk import features as feat
from .risk import interface as risk_if
from .risk.portfolio import portfolio_risk
from .utils import Timer, is_intraday, jsonable, normalize_symbol, period_to_start, utcnow

log = logging.getLogger(__name__)

DISCLAIMER = ("Educational analysis generated by the ABG Intelligence Terminal. Not investment advice. "
              "Data may be delayed, incomplete, or (in demo mode) simulated.")
_BUCKETS = [800, 1900, 3700]          # canonical history windows (days) -> high cache reuse


@dataclass
class AnalyzeOptions:
    period: str = "1y"
    interval: str = "1d"
    source: str | None = None           # force one provider for history/quote
    news: bool = True
    options: bool = True
    fundamentals: bool = True
    ai: bool = True
    benchmark: bool = True
    risk: bool = True
    expiry: date | None = None
    include_series: bool = False        # embed chart series (dashboard) in the report
    position: dict | None = None
    use_cache: bool = True
    live_quote: Quote | None = None     # use this quote instead of fetching one (live monitor)
    history_ttl: float | None = None    # override daily-history cache TTL (monitor reuses history for hours)
    splice_live: bool = True            # merge the live quote into today's daily bar before computing
    forecast: bool = True               # Monte Carlo prediction + thesis / confidence / recommendation
    forecast_horizon: int | None = None # primary horizon in trading days (default ABG_FORECAST_HORIZON)
    forecast_paths: int | None = None


class AnalysisEngine:
    def __init__(self, settings: Settings | None = None, providers: list[Provider] | None = None,
                 http: HttpClient | None = None, cache: TieredCache | None = None):
        self.settings = settings or get_settings()
        s = self.settings
        logging.getLogger("abg").setLevel(s.log_level.upper())
        self.http = http or HttpClient(s.http_timeout, s.connect_timeout, s.user_agent, s.max_connections)
        self.cache = cache or TieredCache(s.cache_dir, s.memory_cache_entries, s.cache_enabled)
        self.providers = providers if providers is not None else build_providers(s, self.http)
        self.router = ProviderRouter(self.providers, s, self.cache)
        risk_if.discover(s.extra_risk_models())

    async def __aenter__(self) -> "AnalysisEngine":
        return self

    async def __aexit__(self, *exc) -> None:
        await self.aclose()

    async def aclose(self) -> None:
        for p in self.providers:
            try:
                await p.aclose()
            except Exception:
                pass
        await self.http.aclose()
        self.cache.close()

    # ================================================================== data access
    def _window(self, period: str, interval: str, end: date) -> date:
        want = period_to_start(period, end)
        if is_intraday(interval):
            return want
        need = (end - want).days + self.settings.warmup_days
        for b in _BUCKETS:
            if need <= b:
                return end - timedelta(days=b)
        return date(1970, 1, 1)

    async def history(self, symbol: str, period: str = "1y", interval: str = "1d", source: str | None = None,
                      use_cache: bool = True, warmup: bool = True, ttl: float | None = None) -> Fetched[PriceHistory]:
        sym = normalize_symbol(symbol)
        end = utcnow().date()
        start = self._window(period, interval, end) if warmup else period_to_start(period, end)
        if ttl is None:
            ttl = self.settings.ttl_history_intraday if is_intraday(interval) else self.settings.ttl_history_daily

        def validate(ph: PriceHistory) -> None:
            if len(ph) < 2:
                raise DataValidationError(f"only {len(ph)} bars", provider=ph.source)

        return await self.router.fetch(
            Capability.HISTORY, sym, lambda p: p.get_history(sym, start, end, interval),
            key=f"{interval}:{start}:{end}", ttl=ttl, interval=interval, only=source, validate=validate, use_cache=use_cache)

    async def quote(self, symbol: str, source: str | None = None, use_cache: bool = True) -> Fetched[Quote]:
        sym = normalize_symbol(symbol)
        return await self.router.fetch(Capability.QUOTE, sym, lambda p: p.get_quote(sym), key="q",
                                       ttl=self.settings.ttl_quote, only=source, use_cache=use_cache, persist=False)

    async def news(self, symbol: str, limit: int | None = None) -> Fetched[list[NewsItem]]:
        sym = normalize_symbol(symbol)
        n = limit or self.settings.news_limit
        return await self.router.fetch(Capability.NEWS, sym, lambda p: p.get_news(sym, n), key=str(n),
                                       ttl=self.settings.ttl_news)

    async def fundamentals(self, symbol: str) -> Fetched[Fundamentals]:
        sym = normalize_symbol(symbol)
        return await self.router.fetch(Capability.FUNDAMENTALS, sym, lambda p: p.get_fundamentals(sym), key="f",
                                       ttl=self.settings.ttl_fundamentals)

    async def option_chain(self, symbol: str, expiry: date | None = None) -> Fetched[OptionChain]:
        sym = normalize_symbol(symbol)
        return await self.router.fetch(Capability.OPTIONS, sym, lambda p: p.get_options(sym, expiry),
                                       key=str(expiry or "near"), ttl=self.settings.ttl_options, persist=False)

    # ================================================================== analysis
    async def analyze(self, symbol: str, opts: AnalyzeOptions | None = None, **kw) -> dict:
        o = opts or AnalyzeOptions(**kw)
        sym = normalize_symbol(symbol)
        timer = Timer()
        warnings: list[str] = []
        prov: list[dict] = []

        async def guard(name: str, coro):
            try:
                return await coro
            except ABGError as e:
                warnings.append(f"{name}: {e.message}")
            except Exception as e:  # pragma: no cover - defensive
                log.exception("%s failed", name)
                warnings.append(f"{name}: unexpected {type(e).__name__}: {e}")
            return None

        bench_sym = self.settings.benchmark
        with timer.stage("fetch"):
            hist_task = asyncio.ensure_future(self.history(sym, o.period, o.interval, o.source, o.use_cache,
                                                           ttl=o.history_ttl))
            side = {
                "quote": None if o.live_quote is not None else guard("quote", self.quote(sym, o.source, o.use_cache)),
                "news": guard("news", self.news(sym)) if o.news else None,
                "fundamentals": guard("fundamentals", self.fundamentals(sym)) if o.fundamentals else None,
                "options": guard("options", self.option_chain(sym, o.expiry)) if o.options else None,
                "benchmark": guard("benchmark", self.history(bench_sym, o.period, o.interval, ttl=o.history_ttl))
                if (o.benchmark and sym != bench_sym) else None,
            }
            side = {k: v for k, v in side.items() if v is not None}
            side_tasks = {k: asyncio.ensure_future(v) for k, v in side.items()}
            try:
                hist: Fetched[PriceHistory] = await hist_task
            except BaseException:
                for t in side_tasks.values():
                    t.cancel()
                raise
            got = dict(zip(side_tasks, await asyncio.gather(*side_tasks.values())))
            if o.live_quote is not None:
                got["quote"] = Fetched(o.live_quote, Provenance("quote", sym, o.live_quote.source, 0.0, "live"))

        for f in [hist, *got.values()]:
            if isinstance(f, Fetched):
                prov.append(jsonable(f.provenance))
                if f.provenance.cache == "stale":
                    warnings.append(f"{f.provenance.capability}: all providers failed, serving cached data "
                                    f"{f.provenance.age_s:.0f}s old")
        return await self._build_report(sym, hist.value, got, o, timer, warnings, prov)

    async def analyze_history(self, ph: PriceHistory, opts: AnalyzeOptions | None = None) -> dict:
        """Analyse caller-supplied bars (e.g. an uploaded CSV).  Network sections are
        attempted only if the symbol looks like a real ticker and the options ask for them."""
        o = opts or AnalyzeOptions(news=False, options=False, fundamentals=False, benchmark=False)
        return await self._build_report(ph.symbol, ph, {}, o, Timer(), [], [
            {"capability": "history", "symbol": ph.symbol, "provider": ph.source, "cache": "n/a"}])

    async def analyze_csv(self, text: str, symbol: str = "CSV", opts: AnalyzeOptions | None = None) -> dict:
        return await self.analyze_history(parse_price_csv(text, normalize_symbol(symbol), "upload"), opts)

    async def _build_report(self, sym: str, ph: PriceHistory, got: dict, o: AnalyzeOptions, timer: Timer,
                            warnings: list[str], prov: list[dict]) -> dict:
        val = lambda k: got[k].value if isinstance(got.get(k), Fetched) else None  # noqa: E731
        quote: Quote | None = val("quote")
        news_items: list[NewsItem] = val("news") or []
        fund: Fundamentals | None = val("fundamentals")
        chain: OptionChain | None = val("options")
        bench: PriceHistory | None = val("benchmark")
        s = self.settings

        with timer.stage("compute"):
            computed = await asyncio.to_thread(self._compute, sym, ph, quote, news_items, fund, chain, bench, o, warnings)

        report: dict[str, Any] = computed["report"]
        fv: feat.FeatureVector = computed["features"]
        if o.risk:
            with timer.stage("risk"):
                ctx = risk_if.RiskContext(symbol=sym, prices=computed["ind"], returns=computed["ind"]["close"].pct_change(fill_method=None),
                                          benchmark_returns=bench.df["close"].pct_change(fill_method=None) if bench else None,
                                          feature_frame=computed["frame"], position=o.position)
                report["risk"] = jsonable(await risk_if.run_models(fv, ctx))
                for r in report["risk"]:
                    if "error" in r:
                        warnings.append(f"risk model {r['model']}: {r['error']}")
        if (report.get("forecast") or {}).get("available"):
            with timer.stage("forecast_rec"):
                report["forecast"] = jsonable(fcast.finalize(report, s.risk_free_rate))
        with timer.stage("insight"):
            if o.ai:
                try:
                    report["ai_insight"] = jsonable(await asyncio.wait_for(
                        claude_insight(report, s, self.http, self.cache), s.ai_timeout + 5))
                except asyncio.TimeoutError:
                    report["ai_insight"] = {**rule_based_insight(report), "note": "Claude timed out; rule-based insight shown."}
            else:
                report["ai_insight"] = rule_based_insight(report)
        report["provenance"] = prov
        report["warnings"] = warnings
        report["timings_ms"] = {**timer.stages, "total": timer.total_ms()}
        return jsonable(report)

    # ------------------------------------------------------------------ pure compute (worker thread)
    def _compute(self, sym, ph: PriceHistory, quote, news_items, fund, chain, bench, o: AnalyzeOptions,
                 warnings: list[str]) -> dict:
        s = self.settings
        intraday = is_intraday(ph.interval)
        ppy = stats.periods_per_year(ph.interval)
        live_bar = None
        if o.splice_live and quote is not None and ph.interval == "1d" and not ph.synthetic:
            df2, live_bar = splice_quote(ph.df, quote)
            if live_bar == "rejected":
                warnings.append(f"live quote {quote.price:.2f} from {quote.source} differs >40% from last close; ignored")
                live_bar = None
            elif live_bar:
                ph = PriceHistory(ph.symbol, df2, ph.interval, ph.source, ph.synthetic, ph.currency, dict(ph.meta))
        ind = ta.compute_all(ph.df, intraday=intraday)
        display_start = period_to_start(o.period, ph.df.index[-1].date() if not intraday else utcnow().date())
        view = ind[ind.index >= pd.Timestamp(display_start)]
        if len(view) < 2:
            view = ind
        bench_close = bench.df["close"] if bench is not None else None

        if quote is None:
            last, prev = ph.df.iloc[-1], ph.df.iloc[-2]
            quote = Quote(symbol=sym, price=float(last["close"]), source=f"{ph.source} (last bar)",
                          prev_close=float(prev["close"]), open=float(last["open"]), day_high=float(last["high"]),
                          day_low=float(last["low"]), volume=float(last["volume"]), synthetic=ph.synthetic,
                          timestamp=ph.last_date.to_pydatetime().replace(tzinfo=timezone.utc))

        sig = signals.composite_signal(ind)
        regime = signals.market_regime(ind)
        plays = signals.classify_plays(ind)
        levels = stats.support_resistance(ph.df)
        st = stats.summary(view["close"], ph.interval, s.risk_free_rate,
                           bench_close.loc[bench_close.index >= view.index[0]] if bench_close is not None else None)
        sentiment = sent.analyze_news(news_items)

        # options: market chain if we have one, otherwise a clearly-flagged model chain
        options_out: dict = {"available": False}
        if o.options:
            try:
                q = (fund.dividend_yield if fund and fund.dividend_yield else s.dividend_yield_default)
                if q > 0.25:                      # vendor sent a percentage, not a decimal
                    q = q / 100
                if chain is None:
                    rv = stats.realized_vol(ph.df["close"], 60, ppy) or stats.realized_vol(ph.df["close"], 20, ppy) or 0.3
                    chain = opt.theoretical_chain(sym, quote.price, rv, s.risk_free_rate, q)
                    warnings.append("options: no market chain available - showing Black-Scholes model chain from realised vol")
                options_out = opt.analyze_chain(chain, s.risk_free_rate, q, expiry=o.expiry)
            except Exception as e:
                warnings.append(f"options analytics: {type(e).__name__}: {e}")

        fund_d = fund.to_dict() if fund else None
        frame = feat.build_feature_frame(ind, bench_close, ppy)
        fv = feat.build_features(sym, ind, bench_close, sentiment=sentiment, options=options_out,
                                 fundamentals=fund_d, signal=sig, ppy=ppy, frame=frame)
        last_age = (utcnow().replace(tzinfo=None) - ph.last_date.to_pydatetime()).days
        if not intraday and last_age > 5:
            warnings.append(f"history: last bar is {last_age} days old")
        if ph.synthetic:
            warnings.insert(0, "DEMO MODE: price data is SIMULATED (synthetic provider). Do not use for decisions.")

        report = {
            "symbol": sym, "name": (fund.name if fund and fund.name else quote.name) or ph.meta.get("name"),
            "as_of": ph.last_date, "generated_at": utcnow(), "period": o.period, "interval": ph.interval,
            "data_quality": {"synthetic": bool(ph.synthetic), "bars_total": len(ph), "bars_in_view": len(view),
                             "first_bar": view.index[0], "last_bar": ph.last_date, "last_bar_age_days": last_age,
                             "history_source": ph.source, "live_bar": live_bar, **({"csv_format": ph.meta["csv_format"]} if "csv_format" in ph.meta else {})},
            "quote": quote.to_dict(), "fundamentals": fund_d,
            "signal": sig, "regime": regime, "plays": plays, "levels": levels,
            "indicators": ta.latest_snapshot(ind), "statistics": st,
            "sentiment": sentiment, "news": [n.to_dict() for n in news_items],
            "options": options_out, "features": fv.to_dict(), "risk": [], "disclaimer": DISCLAIMER,
            "forecast": self._forecast(sym, ph, st, sig, sentiment, plays, o, warnings),
        }
        if o.include_series:
            report["series"] = series_payload(view)
        return {"report": report, "features": fv, "ind": ind, "frame": frame}

    def _forecast(self, sym, ph: PriceHistory, st: dict, sig: dict, sentiment: dict, plays: list,
                  o: AnalyzeOptions, warnings: list[str]) -> dict:
        if not o.forecast:
            return {"available": False, "reason": "disabled"}
        if ph.interval != "1d":
            return {"available": False, "reason": "prediction runs on daily bars (use interval 1d)"}
        s = self.settings
        cfg = fcast.ForecastConfig(paths=o.forecast_paths or s.forecast_paths,
                                   primary_horizon=o.forecast_horizon or s.forecast_horizon,
                                   equity_premium=s.forecast_equity_premium, signal_tilt=s.forecast_signal_tilt)
        try:
            return fcast.simulate(ph.df["close"], symbol=sym, rf=s.risk_free_rate, beta=st.get("beta"),
                                  signal_score=sig.get("score"), sentiment=(sentiment or {}).get("score"),
                                  plays=plays, cfg=cfg)
        except Exception as e:  # never let the forecast take the report down
            log.exception("forecast failed for %s", sym)
            warnings.append(f"forecast: {type(e).__name__}: {e}")
            return {"available": False, "reason": str(e)}

    # ================================================================== multi-symbol
    async def analyze_many(self, symbols: list[str], concurrency: int = 4, **kw) -> dict[str, dict]:
        sem = asyncio.Semaphore(concurrency)

        async def one(sym: str):
            async with sem:
                try:
                    return sym, await self.analyze(sym, **kw)
                except ABGError as e:
                    return sym, {"symbol": sym, "error": e.to_dict()}
        return dict(await asyncio.gather(*(one(s) for s in symbols)))

    async def compare(self, symbols: list[str], period: str = "1y", weights: dict[str, float] | None = None,
                      ai: bool = False) -> dict:
        syms = [normalize_symbol(s) for s in symbols]
        reports = await self.analyze_many(syms, period=period, ai=ai, options=False, news=True)
        closes = {}
        for s in syms:
            try:
                h = (await self.history(s, period)).value
                closes[s] = h.df["close"][h.df.index >= pd.Timestamp(period_to_start(period))]
            except ABGError:
                pass
        port = portfolio_risk(pd.DataFrame(closes).dropna(how="all"), weights) if closes else {"available": False}
        rows = []
        for s in syms:
            r = reports[s]
            if "error" in r:
                rows.append({"symbol": s, "error": r["error"]["message"]})
                continue
            risk = (r.get("risk") or [{}])[0]
            rows.append({"symbol": s, "price": r["quote"]["price"], "change_pct": r["quote"].get("change_pct"),
                         "signal": r["signal"]["score"], "label": r["signal"]["label"], "trend": r["regime"]["trend"],
                         "rsi": r["indicators"].get("rsi_14"), "return_pct": r["statistics"].get("total_return_pct"),
                         "vol_pct": r["statistics"].get("ann_volatility_pct"), "sharpe": r["statistics"].get("sharpe"),
                         "max_dd_pct": r["statistics"].get("max_drawdown_pct"), "risk_score": risk.get("score"),
                         "risk_level": risk.get("level"), "sentiment": r["sentiment"].get("score"),
                         "top_play": r["plays"][0]["name"] if r["plays"] else None})
        return jsonable({"period": period, "rows": rows, "portfolio": port, "reports": reports})

    async def feature_frame(self, symbol: str, period: str = "5y", labels: bool = False,
                            horizons: tuple[int, ...] = (5, 21)) -> pd.DataFrame:
        """Historical, schema-conformant feature matrix for training risk models."""
        sym = normalize_symbol(symbol)
        h = (await self.history(sym, period)).value
        bench = None
        if sym != self.settings.benchmark:
            try:
                bench = (await self.history(self.settings.benchmark, period)).value.df["close"]
            except ABGError:
                pass
        ind = ta.compute_all(h.df)
        frame = feat.build_feature_frame(ind, bench)
        if labels:
            frame = feat.add_forward_labels(frame, h.df["close"], horizons)
        frame = frame[frame.index >= pd.Timestamp(period_to_start(period))]
        frame.insert(0, "symbol", sym)
        frame.attrs["schema_version"] = feat.FEATURE_SCHEMA_VERSION
        return frame

    def status(self) -> dict:
        return {"providers": self.router.status(), "cache": self.cache.stats(),
                "risk_models": [{"name": m.name, "version": m.version} for m in risk_if.registered_models()],
                "feature_schema": feat.FEATURE_SCHEMA_VERSION, "ai": {"enabled": self.settings.ai_enabled,
                "configured": bool(self.settings.anthropic_api_key), "model": self.settings.anthropic_model}}


def splice_quote(df: pd.DataFrame, q: Quote, tz: str = "America/New_York") -> tuple[pd.DataFrame, str | None]:
    """Merge a live quote into daily bars so indicators reflect *today*, not yesterday's close.

    EOD vendors (Tiingo, Stooq...) only publish today's bar after the close, so during the
    session the latest bar is yesterday's.  Returns (df, action) where action is
    'updated' (today's bar already existed), 'appended' (new bar for today), 'rejected'
    (implausible jump - likely a bad tick or unadjusted split) or None (quote not newer).
    """
    if q is None or not q.price or df.empty:
        return df, None
    ts = pd.Timestamp(q.timestamp) if q.timestamp else pd.Timestamp.now(tz="UTC")
    if ts.tzinfo is None:
        ts = ts.tz_localize("UTC")
    day = ts.tz_convert(tz).normalize().tz_localize(None)
    if day.weekday() >= 5:
        return df, None
    last_day = df.index[-1].normalize()
    last_close = float(df["close"].iloc[-1])
    if abs(q.price / last_close - 1) > 0.40:
        return df, "rejected"
    price = float(q.price)
    if day < last_day:
        return df, None
    out = df.copy()
    if day == last_day:
        i = out.index[-1]
        out.loc[i, "close"] = price
        out.loc[i, "high"] = max(float(out.loc[i, "high"]), price, q.day_high or price)
        out.loc[i, "low"] = min(float(out.loc[i, "low"]), price, q.day_low or price)
        if q.volume:
            out.loc[i, "volume"] = max(float(out.loc[i, "volume"]), float(q.volume))
        if "adj_close" in out:
            out.loc[i, "adj_close"] = price
        return out, "updated"
    op = q.open or last_close
    row = {"open": op, "high": max(price, op, q.day_high or price), "low": min(price, op, q.day_low or price),
           "close": price, "volume": float(q.volume or 0.0)}
    if "adj_close" in out:
        row["adj_close"] = price
    out.loc[day] = pd.Series(row)
    return out.sort_index(), "appended"


def series_payload(view: pd.DataFrame) -> dict:
    """Compact column-oriented series for charting (NaN -> null)."""
    idx = view.index
    t = [int(ts.timestamp()) for ts in idx]
    cols = ["open", "high", "low", "close", "volume", "sma_20", "sma_50", "sma_200", "ema_21", "bb_upper", "bb_mid",
            "bb_lower", "vwap_20", "rsi_14", "macd", "macd_signal", "macd_hist", "adx", "plus_di", "minus_di",
            "obv", "stoch_k", "stoch_d", "williams_r", "cci_20", "mfi_14", "atr_14"]
    out = {"time": t}
    for c in cols:
        if c in view:
            arr = view[c].to_numpy(dtype=float)
            out[c] = [None if not np.isfinite(x) else round(float(x), 4) for x in arr]
    return out
